spring.application.name=expense_manager


#kinde.client.id=7b15f5ba43984ecdac7288f112b2dc9e
#kinde.client.secret=OcQ7SumG7qr0dKBk9LD4Beugpxv4E0Z9nMYHLiSYDCUDyaYdvVq
#kinde.host=https://kunwarjora.kinde.com
#kinde.redirect.url=http://localhost:8080/api/auth/kinde_callback
#kinde_post.logout.redirect.url=http://localhost:8080
#KINDE_SCOPE=profile email offline openid