spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Use 'validate' since we managed scripts using Supabase dashboard directly
    show-sql: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KINDE-ISSUER-URL}
          audiences: ${KINDE-AUDIENCE}
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE